### ISSUE TITLE
API breaks on "logical address changed to Broadcast (f)"

### ISSUE THREAD

**Issue by simonfelding** [trainman419/python-cec#47]
I'm running python 3.7.3, the latest python-cec from pip and libCEC 4.0.4.

I've written a simple script to turn on kodi when the TV turns on, and turns kodi off when the TV turns off.
It's gotten a bit complicated because I've been trying to work around this bug. I first found it when I used `while tv.is_on():`; it goes to the unknown state after kodi closes and breaks (it should remember the state of off until it becomes on again, so it always returns false if the TV is off right?).
I worked around it by using the callback function to listen for TV on and off messages. It still can't restart after kodi has been stopped. When I watch the log, it always ends like this:
`
>> 0f:36
TV is off
tv is off. stopping kodi
sleep while off
logical address changed to Broadcast (f)`

and I've narrowed the bug down to the address change - it seems the cec client just dies at this point.
It's probably because my TV goes to deep sleep and it confuses the cec client so much that it disconnects without being able to reconnect without being reinitialised - this workaround is currently in my code, but it's pretty messy.

This issue only appears when kodi exits by the way. I've seen similar reports on the internet when googling `logical address changed to Broadcast (f)`

[Here is my code.](https://github.com/simonfelding/kodi-cec-start-stop/blob/main/main.py)

**Comment by trainman419** [comment]
I haven't seen anything like this before, but it's been a while since I used this library myself.

It looks like the `logical address changed to Broadcast (f)` message is originating within the libCEC library and this is just a relatively simply python wrapper around that library, so I'm not really sure there's anything we can do about it. It is probably better to ask the libCEC maintainers for advice.

**Comment by simonfelding** [comment]
Yeah, you're right. Thanks!
